### PR TITLE
Ignore messages without message_attributes

### PR DESCRIPTION
**Pull request by runningman84**
This fixes issue https://github.com/SimpleFinance/sensu-transport-snssqs/issues/9

### CODE REVIEW

**Comment by tomwans** [comment]
In what case are there no message attributes?

**Comment by runningman84** [comment]
If you get non raw messages...

**Comment by tomwans** [comment]
I've listed in the Caveats section of the README that the "Raw" mode is required (https://github.com/SimpleFinance/sensu-transport-snssqs#caveats). 

That said, I still don't know how the message attributes would be missing from messages, since the message attributes are always requested from the SQS API: https://github.com/runningman84/sensu-transport-snssqs/blob/1883bd52c332730aeb2fd1d21b3525722e109740/lib/sensu/transport/snssqs.rb#L173. Are you using the SQS queue for more than just these Sensu messages?

**Comment by runningman84** [comment]
This pull request is obsolete. We pushed support for non raw messages and better error handling here
https://github.com/troyready/sensu-transport-snssqs-ng/pull/2

**Pull request closed without merging**
